#!/usr/bin/env bash
set -eo pipefail; [[ $RELEASE_TRACE ]] && set -x

PACKAGE_NAME='fuzzywuzzy-java'
VERSION_SOURCE='pom.xml'
PUBLIC="true"

# Colors
COLOR_OFF="\033[0m"   # unsets color to term fg color
RED="\033[0;31m"      # red
GREEN="\033[0;32m"    # green
YELLOW="\033[0;33m"   # yellow
MAGENTA="\033[0;35m"  # magenta
CYAN="\033[0;36m"     # cyan

command -v mvn >/dev/null 2>&1 || {
    echo -e "${RED}WARNING: Missing mvn binary, please install Maven 3.9 or newer${COLOR_OFF}\n"
    exit 1
}

command -v git >/dev/null 2>&1 || {
    echo -e "${RED}WARNING: Missing git binary${COLOR_OFF}\n"
    exit 1
}

set +e;
mvn -q verify &> /dev/null  # run the tests
if [ ! $? -eq 0 ]; then
    echo -e "${RED}WARNING: The tests are failing.${COLOR_OFF}"
    exit 1
fi
set -e;

if [[ "$@" != "major" ]] && [[ "$@" != "minor" ]] && [[ "$@" != "patch" ]]; then
    echo -e "${RED}WARNING: Invalid release type, must specify 'major', 'minor', or 'patch'${COLOR_OFF}\n"
    exit 1
fi

echo -e "\n${GREEN}STARTING RELEASE PROCESS${COLOR_OFF}\n"

set +e;
git status | grep -Eo "working (directory|tree) clean" &> /dev/null
if [ ! $? -eq 0 ]; then # working directory is NOT clean
    echo -e "${RED}WARNING: You have uncomitted changes, you may have forgotten something${COLOR_OFF}\n"
    exit 1
fi
set -e;

echo -e "${YELLOW}--->${COLOR_OFF} Updating local copy"
git pull -q origin master
git fetch --tags > /dev/null

echo -e "${YELLOW}--->${COLOR_OFF} Retrieving release versions"

current_version=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
major=$(echo $current_version | awk '{split($0,a,"."); print a[1]}')
minor=$(echo $current_version | awk '{split($0,a,"."); print a[2]}')
patch=$(echo $current_version | awk '{split($0,a,"."); print a[3]}')

if [[ "$@" == "major" ]]; then
    major=$(($major + 1));
    minor="0"
    patch="0"
elif [[ "$@" == "minor" ]]; then
    minor=$(($minor + 1));
    patch="0"
elif [[ "$@" == "patch" ]]; then
    patch=$(($patch + 1));
fi

next_version="${major}.${minor}.${patch}"

echo -e  "${YELLOW}   >${COLOR_OFF} ${MAGENTA}${current_version}${COLOR_OFF} -> ${MAGENTA}${next_version}${COLOR_OFF}"

echo -e "${YELLOW}--->${COLOR_OFF} Creating necessary temp file"
tempfoo=$(basename $0)
TMPFILE=$(mktemp /tmp/${tempfoo}.XXXXXX) || {
    echo -e "${RED}WARNING: Cannot create temp file using mktemp in /tmp dir ${COLOR_OFF}\n"
    exit 1
}

echo -e "${YELLOW}--->${COLOR_OFF} Updating ${VERSION_SOURCE}"
mvn -q versions:set -DnewVersion=${next_version} -DgenerateBackupPoms=false

echo -e "${YELLOW}--->${COLOR_OFF} Updating FuzzyWuzzy.VERSION"
version_file='src/main/java/com/seatgeek/fuzzywuzzy/FuzzyWuzzy.java'
find_this="VERSION = \"$current_version\""
replace_with="VERSION = \"$next_version\""
sed "s/$find_this/$replace_with/" $version_file > $TMPFILE && mv $TMPFILE $version_file

echo -e "${YELLOW}--->${COLOR_OFF} Updating README.md"
find_this="${PACKAGE_NAME}<\/artifactId>\n.*<version>$current_version"
replace_with="${PACKAGE_NAME}<\/artifactId>\n    <version>$next_version"
TMPFILE=$(mktemp /tmp/${tempfoo}.XXXXXX)
sed "s/<version>$current_version<\/version>/<version>$next_version<\/version>/" README.md > $TMPFILE && mv $TMPFILE README.md

echo -e "${YELLOW}--->${COLOR_OFF} Updating CHANGES.rst for new release"
version_header="$next_version ($(date +%F))"
set +e; dashes=$(yes '-'|head -n ${#version_header}|tr -d '\n') ; set -e
TMPFILE=$(mktemp /tmp/${tempfoo}.XXXXXX)
{
    head -n 3 CHANGES.rst
    echo "$version_header"
    echo "$dashes"
    echo ""
    git log --pretty=format:'- %s [%an]' ${current_version}..HEAD 2> /dev/null || true
    echo ""
    tail -n +4 CHANGES.rst
} > $TMPFILE && mv $TMPFILE CHANGES.rst

echo -e "${YELLOW}--->${COLOR_OFF} Adding changed files to git"
git add CHANGES.rst README.md pom.xml $version_file

echo -e "${YELLOW}--->${COLOR_OFF} Creating release"
git commit -q -m "Release version $next_version"

echo -e "${YELLOW}--->${COLOR_OFF} Tagging release"
git tag -a $next_version -m "Release version $next_version"

echo -e "${YELLOW}--->${COLOR_OFF} Pushing release and tags to github"
git push -q origin master && git push -q --tags

if [[ "$PUBLIC" == "true" ]]; then
    echo -e "${YELLOW}--->${COLOR_OFF} Creating java release"
    mvn -q clean deploy > /dev/null
else
    echo -e "${YELLOW}--->${COLOR_OFF} Creating local jar and sources jar for manual release"
    mvn -q clean verify > /dev/null
fi

echo -e "\n${CYAN}RELEASED VERSION ${next_version}${COLOR_OFF}\n"
