package com.seatgeek.fuzzywuzzy;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.zip.GZIPInputStream;

/**
 * Reads the tab-separated fixtures generated by the scripts under {@code tools/} against the real
 * Python packages.
 */
final class GoldenFixture {

    private GoldenFixture() {
    }

    /**
     * Replays the same assertions against a freshly generated, much larger corpus that is too big
     * to check in. Set {@code -Dfuzzywuzzy.goldenDir=/some/dir} to read fixtures from there.
     */
    private static final String OVERRIDE_DIR = System.getProperty("fuzzywuzzy.goldenDir");

    static List<String[]> readRows(String resource) {
        List<String[]> rows = new ArrayList<>();
        try (InputStream raw = open(resource)) {
            if (raw == null) {
                throw new IllegalStateException("missing fixture: " + resource);
            }
            InputStream in = resource.endsWith(".gz") ? new GZIPInputStream(raw) : raw;
            try (BufferedReader reader =
                         new BufferedReader(new InputStreamReader(in, StandardCharsets.US_ASCII))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    if (!line.isEmpty()) {
                        rows.add(line.split("\t", -1));
                    }
                }
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return rows;
    }

    private static InputStream open(String resource) throws IOException {
        if (OVERRIDE_DIR != null) {
            Path path = Path.of(OVERRIDE_DIR, resource.substring(resource.lastIndexOf('/') + 1));
            if (Files.isReadable(path)) {
                return Files.newInputStream(path);
            }
        }
        return GoldenFixture.class.getResourceAsStream(resource);
    }

    static String decode(String base64) {
        return new String(Base64.getDecoder().decode(base64), StandardCharsets.UTF_8);
    }
}
