package com.seatgeek.fuzzywuzzy;

import com.seatgeek.fuzzywuzzy.internal.PyMath;
import com.seatgeek.fuzzywuzzy.internal.PyStr;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.BitSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exhaustive parity checks for the character-level primitives, against oracles generated by running
 * CPython 3.14 over every one of the 1,114,112 Unicode code points.
 *
 * <p>These are the foundation of the whole port: if {@code isWord}, {@code isSpace} or {@code lower}
 * disagree with Python on even one code point, every downstream ratio can silently diverge.
 */
class PyStrGoldenTest {

    private static final int MAX_CODE_POINT = 0x110000;

    private static BufferedReader open(String resource) {
        InputStream in = PyStrGoldenTest.class.getResourceAsStream(resource);
        if (in == null) {
            throw new IllegalStateException("missing golden resource: " + resource);
        }
        return new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
    }

    private static BitSet readRanges(String resource) throws IOException {
        BitSet set = new BitSet(MAX_CODE_POINT);
        try (BufferedReader r = open(resource)) {
            String line;
            while ((line = r.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') {
                    continue;
                }
                int sp = line.indexOf(' ');
                int lo = Integer.parseInt(line.substring(0, sp), 16);
                int hi = Integer.parseInt(line.substring(sp + 1), 16);
                set.set(lo, hi + 1);
            }
        }
        return set;
    }

    @Test
    @DisplayName("PyStr.isWord matches Python re '(?ui)\\w' on all 1,114,112 code points")
    void wordPredicateMatchesPythonOnEveryCodePoint() throws IOException {
        BitSet expected = readRanges("/golden/word_ranges.txt");
        List<String> failures = new ArrayList<>();
        for (int cp = 0; cp < MAX_CODE_POINT; cp++) {
            if (PyStr.isWord(cp) != expected.get(cp)) {
                failures.add(String.format("U+%04X python=%s java=%s type=%d",
                        cp, expected.get(cp), PyStr.isWord(cp), Character.getType(cp)));
                if (failures.size() >= 25) {
                    break;
                }
            }
        }
        assertTrue(failures.isEmpty(), () -> "isWord divergence: " + failures);
    }

    @Test
    @DisplayName("PyStr.isSpace matches Python str.isspace() on all 1,114,112 code points")
    void spacePredicateMatchesPythonOnEveryCodePoint() throws IOException {
        BitSet expected = readRanges("/golden/space_ranges.txt");
        List<String> failures = new ArrayList<>();
        for (int cp = 0; cp < MAX_CODE_POINT; cp++) {
            if (PyStr.isSpace(cp) != expected.get(cp)) {
                failures.add(String.format("U+%04X python=%s java=%s", cp, expected.get(cp), PyStr.isSpace(cp)));
                if (failures.size() >= 25) {
                    break;
                }
            }
        }
        assertTrue(failures.isEmpty(), () -> "isSpace divergence: " + failures);
    }

    @Test
    @DisplayName("PyStr.isSpace differs from Character.isWhitespace exactly where Python does")
    void spacePredicateIsNotJavaWhitespace() {
        assertTrue(PyStr.isSpace(0x00A0), "Python counts NBSP as space");
        assertFalse(Character.isWhitespace(0x00A0), "Java does not count NBSP as space");
        assertTrue(PyStr.isSpace(0x001C), "Python counts FILE SEPARATOR as space");
        assertTrue(PyStr.isSpace(0x0085), "Python counts NEL as space");
        assertTrue(PyStr.isSpace(0x2007), "Python counts FIGURE SPACE as space");
        assertFalse(Character.isWhitespace(0x2007), "Java does not count FIGURE SPACE as space");
    }

    /** Absence from the returned map means CPython leaves that code point unchanged. */
    private static Map<Integer, String> readCaseMap(String resource) throws IOException {
        Map<Integer, String> map = new HashMap<>();
        try (BufferedReader r = open(resource)) {
            String line;
            while ((line = r.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') {
                    continue;
                }
                int sp = line.indexOf(' ');
                int cp = Integer.parseInt(line.substring(0, sp), 16);
                StringBuilder sb = new StringBuilder();
                for (String h : line.substring(sp + 1).split(" ")) {
                    sb.appendCodePoint(Integer.parseInt(h, 16));
                }
                map.put(cp, sb.toString());
            }
        }
        return map;
    }

    private void assertCaseMapMatchesPython(String resource, boolean lower) throws IOException {
        Map<Integer, String> oracle = readCaseMap(resource);
        BitSet covered = new BitSet(MAX_CODE_POINT);
        List<String> failures = new ArrayList<>();
        for (Map.Entry<Integer, String> entry : oracle.entrySet()) {
            int cp = entry.getKey();
            String expected = entry.getValue();
            String source = new String(Character.toChars(cp));
            String actual = lower ? PyStr.lower(source) : PyStr.upper(source);
            covered.set(cp);
            if (!expected.equals(actual)) {
                failures.add(String.format("U+%04X python=%s java=%s", cp, hex(expected), hex(actual)));
            }
        }
        // Every code point NOT listed in the oracle must be unchanged by the mapping.
        for (int cp = 0; cp < MAX_CODE_POINT; cp++) {
            if (covered.get(cp)) {
                continue;
            }
            String source = new String(Character.toChars(cp));
            String actual = lower ? PyStr.lower(source) : PyStr.upper(source);
            if (!source.equals(actual)) {
                failures.add(String.format("U+%04X python=unchanged java=%s", cp, hex(actual)));
            }
            if (failures.size() >= 40) {
                break;
            }
        }
        assertTrue(failures.isEmpty(), () -> resource + " divergence (" + failures.size() + "): " + failures);
    }

    /**
     * Every code point on which the running JDK's {@code String.toLowerCase(Locale.ROOT)} disagrees
     * with the CPython 3.14 oracle.
     *
     * <p>The JDK ships an older Unicode revision than CPython (JDK 17 tracks Unicode 13.0, JDK 21
     * tracks 15.0, CPython 3.14 tracks 16.0), so the contents of this set change with the JDK the
     * suite happens to run on. It is therefore discovered from the oracle at run time; hard-coding
     * one JDK's answer would make the test pass on that JDK only.
     */
    private static List<Integer> codePointsWhereJdkLowerDivergesFromPython() throws IOException {
        Map<Integer, String> oracle = readCaseMap("/golden/lower_map.txt");
        List<Integer> divergent = new ArrayList<>();
        for (int cp = 0; cp < MAX_CODE_POINT; cp++) {
            if (cp >= Character.MIN_SURROGATE && cp <= Character.MAX_SURROGATE) {
                continue;
            }
            String source = new String(Character.toChars(cp));
            String python = oracle.getOrDefault(cp, source);
            if (!python.equals(source.toLowerCase(Locale.ROOT))) {
                divergent.add(cp);
            }
        }
        return divergent;
    }

    private static String hex(String s) {
        StringBuilder sb = new StringBuilder();
        s.codePoints().forEach(c -> sb.append(String.format("%04X ", c)));
        return sb.toString().trim();
    }

    @Test
    @DisplayName("PyStr.lower matches Python str.lower() on every code point")
    void lowerMatchesPython() throws IOException {
        assertCaseMapMatchesPython("/golden/lower_map.txt", true);
    }

    @Test
    @DisplayName("PyStr.upper matches Python str.upper() on every code point")
    void upperMatchesPython() throws IOException {
        assertCaseMapMatchesPython("/golden/upper_map.txt", false);
    }

    @Test
    @DisplayName("PyStr.lower resolves Greek final sigma from CPython's own cased-letter table")
    void lowerPreservesSigmaContextAroundDivergentCodePoints() throws IOException {
        assertEquals("\u03bf\u03b4\u03bf\u03c2", PyStr.lower("\u039f\u0394\u039f\u03a3"),
                "sigma ending a word is final");
        assertEquals("\u03b1\u03c2", PyStr.lower("\u0391\u03a3"),
                "sigma ending the string is final");
        assertEquals("\u03b1\u03c3a", PyStr.lower("\u0391\u03a3A"),
                "a cased letter follows, so the sigma is not final");
        assertEquals("\u03b1\u03c2 a", PyStr.lower("\u0391\u03a3 A"),
                "a space is not cased, so the sigma is final");
        assertEquals("\u03b1\u03c2.", PyStr.lower("\u0391\u03a3."),
                "punctuation is not cased, so the sigma is final");
        assertEquals("\u03b1\u03c2\u0301", PyStr.lower("\u0391\u03a3\u0301"),
                "a combining mark is case-ignorable and does not end the word");
        assertEquals("\u03c3", PyStr.lower("\u03a3"),
                "no cased letter precedes the sigma, so it cannot be final");
        assertEquals("\u03c3\u03c2", PyStr.lower("\u03a3\u03a3"),
                "only the trailing sigma of a run is final");
        assertEquals("a\u03c3b", PyStr.lower("A\u03a3B"));
        assertEquals("\u03c3a", PyStr.lower("\u03a3a"));

        List<Integer> divergent = codePointsWhereJdkLowerDivergesFromPython();
        Map<Integer, String> oracle = readCaseMap("/golden/lower_map.txt");
        List<String> delegated = new ArrayList<>();
        for (int cp : divergent) {
            String source = new String(Character.toChars(cp));
            String python = oracle.getOrDefault(cp, source);
            if (!python.equals(PyStr.lower(source))) {
                delegated.add(String.format("U+%04X python=%s pystr=%s jdk=%s",
                        cp, hex(python), hex(PyStr.lower(source)), hex(source.toLowerCase(Locale.ROOT))));
            }
        }
        assertTrue(delegated.isEmpty(),
                () -> "PyStr.lower followed the JDK instead of CPython on " + delegated.size()
                        + " code point(s): " + delegated);
        for (int cp : divergent) {
            String source = new String(Character.toChars(cp));
            assertNotEquals(source.toLowerCase(Locale.ROOT), PyStr.lower(source),
                    () -> String.format("U+%04X is a code point this JDK maps differently from CPython,"
                            + " so a naive toLowerCase would have been wrong here", cp));
        }
    }

    @Test
    @DisplayName("PyStr.split reproduces Python str.split() with no argument")
    void splitMatchesPython() {
        assertEquals(List.of("a", "b"), PyStr.split("  a   b  "));
        assertEquals(List.of(), PyStr.split("   "));
        assertEquals(List.of(), PyStr.split(""));
        assertEquals(List.of("a"), PyStr.split("\u00a0a\u00a0"));
        assertEquals(List.of("a", "b"), PyStr.split("a\u001cb"));
        // Java's String.split("\\s+") would return a leading "" here; Python does not.
        assertEquals(List.of("x"), PyStr.split(" x"));
    }

    @Test
    @DisplayName("PyStr.strip reproduces Python str.strip() including NBSP")
    void stripMatchesPython() {
        assertEquals("a", PyStr.strip("  a  "));
        assertEquals("a", PyStr.strip("\u00a0a\u00a0"));
        assertEquals("", PyStr.strip("\u001c\u001d\u001e\u001f"));
        assertEquals("a b", PyStr.strip(" a b "));
        assertEquals("", PyStr.strip(""));
    }

    @Test
    @DisplayName("PyStr.CODE_POINT_ORDER sorts supplementary characters after U+FFFF like Python")
    void codePointOrderMatchesPython() {
        String astral = new String(Character.toChars(0x1F600));
        String bmpHigh = "\ue000";
        assertTrue(PyStr.compareCodePoints(bmpHigh, astral) < 0,
                "Python orders U+E000 before U+1F600");
        assertTrue(bmpHigh.compareTo(astral) > 0,
                "Java's String.compareTo does the opposite, which is why we need our own comparator");
        List<String> tokens = new ArrayList<>(Arrays.asList(astral, bmpHigh, "a"));
        tokens.sort(PyStr.CODE_POINT_ORDER);
        assertEquals(Arrays.asList("a", bmpHigh, astral), tokens);
    }

    @Test
    @DisplayName("PyStr.slice clamps out-of-range bounds instead of throwing, like a Python slice")
    void sliceClampsLikePython() {
        int[] cps = PyStr.toCodePoints("abc");
        assertEquals("abc", PyStr.slice(cps, 0, 99));
        assertEquals("", PyStr.slice(cps, 5, 99));
        assertEquals("bc", PyStr.slice(cps, 1, 3));
        assertEquals("", PyStr.slice(cps, 2, 2));
    }

    @Test
    @DisplayName("PyStr.len counts code points, not UTF-16 units")
    void lenCountsCodePoints() {
        assertEquals(1, PyStr.len(new String(Character.toChars(0x1F600))));
        assertEquals(2, new String(Character.toChars(0x1F600)).length());
        assertEquals(3, PyStr.len("abc"));
    }

    @Test
    @DisplayName("PyMath.intr uses banker's rounding like Python's round()")
    void intrUsesBankersRounding() {
        assertEquals(66, PyMath.intr(66.5));
        assertEquals(68, PyMath.intr(67.5));
        assertEquals(0, PyMath.intr(0.5));
        assertEquals(2, PyMath.intr(1.5));
        assertEquals(2, PyMath.intr(2.5));
        assertEquals(-2, PyMath.intr(-2.5));
        assertEquals(-4, PyMath.intr(-3.5));
        assertEquals(67, PyMath.intr(66.6));
        assertEquals(66, PyMath.intr(66.4));
        assertEquals(100, PyMath.intr(100.0));
        assertEquals(0, PyMath.intr(0.0));
        // Math.round would give 67 here, which is the classic off-by-one this port must avoid.
        assertEquals(67, Math.round(66.5));
    }

    @Test
    @DisplayName("PyMath.intr does not wrap around for values beyond int range")
    void intrDoesNotWrapBeyondIntRange() {
        assertEquals(1000000000000000L, PyMath.intr(1000000000000000.5));
        assertEquals(1000000000000002L, PyMath.intr(1000000000000001.5));
        assertEquals(2147483648L, PyMath.intr(2147483647.5));
        assertEquals(4294967296L, PyMath.intr(4294967296.4));
        assertEquals(-1000000000000000L, PyMath.intr(-1000000000000000.5));
        assertEquals(1000000000000000L, Utils.intr(1000000000000000.5));
    }
}
